# Generated by Django 5.1.15 on 2026-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("reviewer", "Reviewer"),
                    ("annotator", "Annotator"),
                ],
                db_index=True,
                default="annotator",
                help_text="The role of the user within the organization.",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
